import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu, MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger
} from "@/components/ui/menubar";
import Link from "next/link";
import {Toaster} from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menubar>
          <MenubarMenu>
            <MenubarTrigger>Gallery</MenubarTrigger>
            <MenubarContent>
              <Link href={"/gallery/create"}>
                <MenubarItem>
                  New...
                </MenubarItem>
              </Link>
              <MenubarSeparator />
              <Link href={"/gallery/list"}>
                  <MenubarItem>
                  List
                  </MenubarItem>
              </Link>
            </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
            <MenubarTrigger>Artists</MenubarTrigger>
            <MenubarContent>
              <Link href={"/artist/create"}>
                <MenubarItem>
                  New...
                </MenubarItem>
              </Link>
              <MenubarSeparator />
              <Link href={"/artist/list"}>
                <MenubarItem>
                  List
                </MenubarItem>
              </Link>
            </MenubarContent>
          </MenubarMenu>
        </Menubar>
        <div className={"p-4"}>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
